### ISSUE TITLE
User Accounts

### ISSUE THREAD

**Issue by John-Sudol** [samdindyal/Hunt#4]
## We need a way for users to:
- [x] Create a new account
- [x] Authentication
- [x] Persistent login
- [x] Encrypt password and auth token
- [x] Create views for login/sign up
