### ISSUE TITLE
Setting up a Backend

### ISSUE THREAD

**Issue by John-Sudol** [samdindyal/Hunt#8]
Okay for this part I'm not entirely sure. I'm hoping that Sam can fill in the gaps I have here. 
I'm putting this as one entire epic but I think this will be part of almost every project.

Tasks
- [x] Create project structure for node app
- [x] Install dependencies
- [x] Set up mongo for dev environment
- [x] Create controller for User
- [x] Create model for User
- [x] Create db connection/config file
- [x] Create controller for static pages
